/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import perpustakaan.bukuForm;
import perpustakaan.kategoriForm;
import perpustakaan.memberForm;
import perpustakaan.peminjamanForm;
import perpustakaan.pengambalianForm;

/**
 *
 * @author Gentur
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneContent = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMember = new javax.swing.JMenu();
        jMenuItemMember = new javax.swing.JMenuItem();
        jMenuBuku = new javax.swing.JMenu();
        jMenuItemRecordBuku = new javax.swing.JMenuItem();
        jMenuItemKategori = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemPeminjaman = new javax.swing.JMenuItem();
        jMenuItemPengembalian = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPaneContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneContentLayout = new javax.swing.GroupLayout(jDesktopPaneContent);
        jDesktopPaneContent.setLayout(jDesktopPaneContentLayout);
        jDesktopPaneContentLayout.setHorizontalGroup(
            jDesktopPaneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        jDesktopPaneContentLayout.setVerticalGroup(
            jDesktopPaneContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        jMenuMember.setText("Member");

        jMenuItemMember.setText("Record Member");
        jMenuItemMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMemberActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemMember);

        jMenuBar1.add(jMenuMember);

        jMenuBuku.setText("Buku");
        jMenuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBukuActionPerformed(evt);
            }
        });

        jMenuItemRecordBuku.setText("Record Buku");
        jMenuItemRecordBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecordBukuActionPerformed(evt);
            }
        });
        jMenuBuku.add(jMenuItemRecordBuku);

        jMenuItemKategori.setText("Kategori Buku");
        jMenuItemKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKategoriActionPerformed(evt);
            }
        });
        jMenuBuku.add(jMenuItemKategori);

        jMenuBar1.add(jMenuBuku);

        jMenuTransaksi.setText("Transaksi");

        jMenuItemPeminjaman.setText("Peminjaman");
        jMenuItemPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeminjamanActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPeminjaman);

        jMenuItemPengembalian.setText("Pengembalian");
        jMenuItemPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPengembalianActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPengembalian);

        jMenuBar1.add(jMenuTransaksi);

        jMenuAccount.setText("Account");
        jMenuAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAccountActionPerformed(evt);
            }
        });

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemLogout);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneContent, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneContent)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPengembalianActionPerformed
        // TODO add your handling code here:
        pengambalianForm pf = new pengambalianForm();
        jDesktopPaneContent.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPengembalianActionPerformed

    private void jMenuAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAccountActionPerformed

    private void jMenuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBukuActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        login log = new login();
        JOptionPane.showMessageDialog(null, "Anda berhasil Logout");
        log.setResizable(false);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemRecordBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecordBukuActionPerformed
        // TODO add your handling code here:
        bukuForm b = null;
        try {
            b = new bukuForm();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPaneContent.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_jMenuItemRecordBukuActionPerformed

    private void jMenuItemKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKategoriActionPerformed
        // TODO add your handling code here:
        kategoriForm k = new kategoriForm();
        jDesktopPaneContent.add(k);
        k.setVisible(true);
    }//GEN-LAST:event_jMenuItemKategoriActionPerformed

    private void jMenuItemMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMemberActionPerformed
        // TODO add your handling code here:
        memberForm m = new memberForm();
        jDesktopPaneContent.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuItemMemberActionPerformed

    private void jMenuItemPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeminjamanActionPerformed
        // TODO add your handling code here:
        peminjamanForm p = new peminjamanForm();
        jDesktopPaneContent.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItemPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneContent;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBuku;
    private javax.swing.JMenuItem jMenuItemKategori;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemMember;
    private javax.swing.JMenuItem jMenuItemPeminjaman;
    private javax.swing.JMenuItem jMenuItemPengembalian;
    private javax.swing.JMenuItem jMenuItemRecordBuku;
    private javax.swing.JMenu jMenuMember;
    private javax.swing.JMenu jMenuTransaksi;
    // End of variables declaration//GEN-END:variables
}
